In [1]:
import torch
from torch import Tensor, nn

project_dir = os.path.split(os.getcwd())[0]
if project_dir not in sys.path:
    sys.path.append(project_dir)

ipdl_dir = os.path.join(project_dir, "ipdl/")
if ipdl_dir not in sys.path:
    sys.path.append(ipdl_dir)

from IPAE import MatrixEstimator, SDAE

In [2]:
test_matrix = torch.rand((10,10))

In [3]:
from IPDL.MatrixBasedRenyisEntropy import MutualInformation

class InformationPlane():
    '''
        Pass a list of tensor which contents the matrices in order to calculate the
        MutualInformation
    '''
    def __init__(self, matrix_estimator: list):
        if not all(isinstance(n, MatrixEstimator) for n in matrix_estimator):
            #lanzar error
            pass

        # First element corresponds to input A matrix and last element
        # is the output A matrix
        self.matrices_per_layers = matrix_estimator
        self.Ixt = [[]] * len(matrix_estimator)-2
        self.Iyt = [[]] * len(matrix_estimator)-2
    
    def calculate_mi(self):
        Ax = self.matrices_per_layers[0]
        Ay = self.matrices_per_layers[-1]

        for idx, A in enumerate(self.matrices_per_layers[1:-1]):
            self.Ixt[idx].append(MutualInformation(Ax, A).cpu())
            self.Ity[idx].append(MutualInformation(A, Ay).cpu())

    def get_mi(self):
        return self.Ixt, self.Ity

        





In [6]:
model = SDAE([28*28, 1024, 512, 256, 32], dropout=False)
# print(model)
# print(model.get_matrix_2())

ip = InformationPlane(model.get_matrix())

In [10]:
ip.A[0].A

tensor([[3.8101e-01, 2.1042e-01, 6.6698e-01, 3.9416e-01, 9.6226e-01, 9.5170e-01,
         4.1154e-01, 7.9516e-01, 2.5094e-01, 9.7850e-01],
        [2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02,
         2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02],
        [4.2366e-01, 7.7059e-01, 6.0624e-01, 4.6168e-01, 9.1084e-01, 9.2887e-01,
         7.0689e-01, 4.6169e-01, 5.2903e-02, 8.2253e-01],
        [1.8196e-01, 3.2821e-01, 6.5326e-02, 1.4393e-01, 5.4837e-01, 1.6378e-01,
         9.3653e-01, 7.0106e-01, 5.2061e-02, 2.4938e-01],
        [3.8370e-01, 9.0191e-01, 4.4588e-02, 4.0472e-02, 8.9964e-01, 6.1514e-01,
         5.8521e-01, 7.7165e-01, 8.4367e-01, 5.7231e-02],
        [4.4600e-01, 3.0310e-01, 8.6842e-01, 7.6613e-01, 5.7623e-01, 7.9551e-01,
         7.8189e-01, 6.5655e-01, 5.1016e-01, 6.3854e-01],
        [2.3456e-01, 2.7144e-01, 1.8092e-01, 7.6562e-02, 6.3162e-01, 4.8244e-01,
         5.2851e-01, 1.0406e-01, 3.5921e-01, 9.4406e-01],
        [8.8371e-01, 8.7881

In [9]:
model.get_matrix()[0].A[1]=200
print(model.get_matrix()[0].A)


tensor([[3.8101e-01, 2.1042e-01, 6.6698e-01, 3.9416e-01, 9.6226e-01, 9.5170e-01,
         4.1154e-01, 7.9516e-01, 2.5094e-01, 9.7850e-01],
        [2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02,
         2.0000e+02, 2.0000e+02, 2.0000e+02, 2.0000e+02],
        [4.2366e-01, 7.7059e-01, 6.0624e-01, 4.6168e-01, 9.1084e-01, 9.2887e-01,
         7.0689e-01, 4.6169e-01, 5.2903e-02, 8.2253e-01],
        [1.8196e-01, 3.2821e-01, 6.5326e-02, 1.4393e-01, 5.4837e-01, 1.6378e-01,
         9.3653e-01, 7.0106e-01, 5.2061e-02, 2.4938e-01],
        [3.8370e-01, 9.0191e-01, 4.4588e-02, 4.0472e-02, 8.9964e-01, 6.1514e-01,
         5.8521e-01, 7.7165e-01, 8.4367e-01, 5.7231e-02],
        [4.4600e-01, 3.0310e-01, 8.6842e-01, 7.6613e-01, 5.7623e-01, 7.9551e-01,
         7.8189e-01, 6.5655e-01, 5.1016e-01, 6.3854e-01],
        [2.3456e-01, 2.7144e-01, 1.8092e-01, 7.6562e-02, 6.3162e-01, 4.8244e-01,
         5.2851e-01, 1.0406e-01, 3.5921e-01, 9.4406e-01],
        [8.8371e-01, 8.7881

In [28]:
a = torch.arange(25).reshape(5,5)
b = torch.arange(25, 50).reshape(5,5)
c = [a, b]

True

In [22]:
result = torch.stack(c)
print(result)
result.shape

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]])


torch.Size([2, 5, 5])

In [12]:
m0 = MatrixEstimator(0.8)
m1 = MatrixEstimator(0.8)
m2 = MatrixEstimator(0.8)
m3 = MatrixEstimator(0.8)
A = [m0, m1, m2, m3]
print(A[0].A)

tensor([[0.1504, 0.1226, 0.4118, 0.1564, 0.8514, 0.8295, 0.9161, 0.1021, 0.4262,
         0.4999],
        [0.3770, 0.5399, 0.6297, 0.8608, 0.7491, 0.9401, 0.2194, 0.7682, 0.4176,
         0.9979],
        [0.6599, 0.3895, 0.9410, 0.6254, 0.3814, 0.8940, 0.7112, 0.2609, 0.7171,
         0.6370],
        [0.9899, 0.6683, 0.9308, 0.2607, 0.5643, 0.7218, 0.0067, 0.1014, 0.5282,
         0.1060],
        [0.4552, 0.6025, 0.6440, 0.8796, 0.5812, 0.3284, 0.4586, 0.4851, 0.2083,
         0.8186],
        [0.6865, 0.0070, 0.5949, 0.8452, 0.5313, 0.3779, 0.6941, 0.1704, 0.1797,
         0.8347],
        [0.5058, 0.3210, 0.1708, 0.3698, 0.9904, 0.3283, 0.1075, 0.1902, 0.9411,
         0.6207],
        [0.6188, 0.4609, 0.0426, 0.6406, 0.2116, 0.8976, 0.2051, 0.7540, 0.4335,
         0.3616],
        [0.6838, 0.1760, 0.2131, 0.8948, 0.2962, 0.2037, 0.9088, 0.2722, 0.5930,
         0.0078],
        [0.7530, 0.7880, 0.9689, 0.9997, 0.3275, 0.6914, 0.0925, 0.0571, 0.1282,
         0.9383]])


In [13]:
m0.A[0] = 0.05
print(A[0].A)

tensor([[0.0500, 0.0500, 0.0500, 0.0500, 0.0500, 0.0500, 0.0500, 0.0500, 0.0500,
         0.0500],
        [0.3770, 0.5399, 0.6297, 0.8608, 0.7491, 0.9401, 0.2194, 0.7682, 0.4176,
         0.9979],
        [0.6599, 0.3895, 0.9410, 0.6254, 0.3814, 0.8940, 0.7112, 0.2609, 0.7171,
         0.6370],
        [0.9899, 0.6683, 0.9308, 0.2607, 0.5643, 0.7218, 0.0067, 0.1014, 0.5282,
         0.1060],
        [0.4552, 0.6025, 0.6440, 0.8796, 0.5812, 0.3284, 0.4586, 0.4851, 0.2083,
         0.8186],
        [0.6865, 0.0070, 0.5949, 0.8452, 0.5313, 0.3779, 0.6941, 0.1704, 0.1797,
         0.8347],
        [0.5058, 0.3210, 0.1708, 0.3698, 0.9904, 0.3283, 0.1075, 0.1902, 0.9411,
         0.6207],
        [0.6188, 0.4609, 0.0426, 0.6406, 0.2116, 0.8976, 0.2051, 0.7540, 0.4335,
         0.3616],
        [0.6838, 0.1760, 0.2131, 0.8948, 0.2962, 0.2037, 0.9088, 0.2722, 0.5930,
         0.0078],
        [0.7530, 0.7880, 0.9689, 0.9997, 0.3275, 0.6914, 0.0925, 0.0571, 0.1282,
         0.9383]])


In [5]:
    def get_matrix(self) -> list:
        matrix_layers = []
        for seq in self.sdae:
            for module in seq:
                if isinstance(module, MatrixEstimator):
                    matrix_layers.append(module)


test = nn.Sequential(
        nn.Linear(10, 10),
        nn.Sequential(
            nn.Linear(10, 100),
            nn.Linear(100, 200),
            nn.Sequential(
                MatrixEstimator(0.8),
                nn.Linear(200, 10),
            )
        )
    )

In [6]:
print(test)

Sequential(
  (0): Linear(in_features=10, out_features=10, bias=True)
  (1): Sequential(
    (0): Linear(in_features=10, out_features=100, bias=True)
    (1): Linear(in_features=100, out_features=200, bias=True)
    (2): Sequential(
      (0): MatrixEstimator()
      (1): Linear(in_features=200, out_features=10, bias=True)
    )
  )
)


In [8]:
def recurrency(modules):
    result = []
    for module in modules:
        if isinstance(module, (nn.Linear)):
            result.append(module)
        else:
            if isinstance(module, (nn.Sequential)):
                result.extend( recurrency(module) )
        
    return result
        
print(recurrency(test))

[Linear(in_features=10, out_features=10, bias=True), Linear(in_features=10, out_features=100, bias=True), Linear(in_features=100, out_features=200, bias=True), Linear(in_features=200, out_features=10, bias=True)]


In [14]:
Ixt = [[]]*(10-2)
print(Ixt)

[[], [], [], [], [], [], [], []]


In [16]:
a = [10, 2, 3 , 102, 4]
for i in a[1:-1]:
    print(i)

2
3
102


[[1]]
